### ISSUE TITLE
Confidence score for lexical mappings from Gilda

### ISSUE THREAD

**Issue by cthoyt** [biomappings/biomappings#12]
@bgyori Can gilda produce a confidence score for a given lexincal mapping? It might make sense to prioritize curation in the web interface based on this mapping either for easy curation on high confidence ones, or difficult curation on relatively low confidence ones. I assume there's already a cutoff somewhere being applied to remove obviously incorrect lexical mappings.

Funny, I feel like we've gone down this road before both in INDRA's belief scores and also in the rational enrichment paper :)

**Comment by bgyori** [comment]
Yes, I opened an issue for this in #5, we just need to add a column for it in the schema for predictions.tsv.

**Comment by cthoyt** [comment]
My bad, somehow I missed that. Will close this one
