### ISSUE TITLE
MeSH now appears to provide mappings to Taxonomy

### ISSUE THREAD

**Issue by bgyori** [biomappings/biomappings#15]
In the latest, 2021 release of MeSH, there are some new entries that provide mappings from MeSH terms to Taxonomy. I confirmed that this info was not included in the 2020 release. Example: https://meshb.nlm.nih.gov/record/ui?ui=D051379 lists 
```
Registry Number: txid10088
Related Numbers: txid10090
                 txid10092
```
The same information appears in the XML dump of MeSH. This is relevant for https://github.com/biomappings/biomappings/pull/6 which adds some mappings between MeSH and Taxonomy but since these are now available from a "primary" source, they technically shouldn't be added here.

**Comment by cthoyt** [comment]
Wow! I don't think I've looked in the last 2-3 months, but the MeSH 2020 release was non-existent the last time I checked
