### ISSUE TITLE
Species specific mappings

### ISSUE THREAD

**Issue by cthoyt** [biomappings/biomappings#31]
I was starting to do WikiPathways and Reactome mappings to GO and MeSH, but both WikiPathways and Reactome have species-specific identifiers while GO and MeSH do not. Should we make mappings between these?

Perhaps we should start including optional species information in the predictions file for both the source and target when available

**Comment by bgyori** [comment]
Yes, that's really tricky... take for instance the MeSH term https://meshb.nlm.nih.gov/record/ui?ui=D066247, which we already curated as a mapping to https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:3432. But the MeSH term isn't explicitly about a human gene, it could possibly also be interpreted as a cross-species family of genes or proteins. The same is true for GO complexes that aren't necessarily species specific mapped to FPLX complexes that are human-specific. It's possible that some of these would be better captured as `broader`/`narrower` relations.
