### ISSUE TITLE
Github push not working from web interface

### ISSUE THREAD

**Issue by bgyori** [biomappings/biomappings#52]
I started a branch called `curation`, did some curation and then pushed the usual "Commit and Push" button. The commit part worked but the push did not happen. I then manually pushed the branch and tried again after some further curations, and the push still did not happen automatically. I suppose I could print some debug messages from the code running the git commands to see why this might be the case.

**Comment by cthoyt** [comment]
I added some logging to the console for the output of the `git commit` and `git push` commants in 0d2059d, then tried two more curations on your branch. It seemed to be committing and pushing correctly for me. Let me know if that error persists and if you get useful output when it happens again

Below is the code that's running the git commands. I wonder if the redirect to stderr might be eating up some useful feedback:

```
def _git(*args: str) -> Optional[str]:
    with open(os.devnull, "w") as devnull:
        try:
            ret = check_output(  # noqa: S603,S607
                ["git", *args],
                cwd=os.path.dirname(__file__),
                stderr=devnull,
            )
        except CalledProcessError:
            return
        else:
            return ret.strip().decode("utf-8")
```

**Comment by bgyori** [comment]
Logging says this:
```
2021-07-26 09:41:33 WARNING  git commit res: [curation 4c8c7b8] Curated 1 mapping (ben)
 2 files changed, 1 insertion(+), 1 deletion(-)
2021-07-26 09:41:34 WARNING  git push res: None
```
so the commit works but the push returns None, I'll do some debugging to see what actually happens.

**Comment by bgyori** [comment]
Okay, I figured out the issue. It has to do with local settings about how upstreams are interpreted by default based on local settings. In some environments `git push` just works, but in my environment I get

```
fatal: The current branch curation has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin curation
```

The solution, I think, would be to run `git push origin <branch name>` explicitly instead of just `git push`, since that would work irrespective of the environment's upstream settings.

**Comment by bgyori** [comment]
@cthoyt see https://github.com/biomappings/biomappings/pull/53/commits/d6d22f149c94fbf54694b972dff34cca6571d54f for my solution.
