### ISSUE TITLE
Curation interface

### ISSUE THREAD

**Issue by bgyori** [biomappings/biomappings#7]
Not sure if @cthoyt already gave this some thought but I'm wondering if we could set up a UI to support quickly vetting predicted curations, e.g., an small webapp where you put in your ORCID and can check correct/incorrect next to a list of predicted mappings (with link out URLs if they need to be followed up on) and then click a button to get a TSV export you can commit to the manual mappings table.

**Comment by cthoyt** [comment]
Closed by #11
